# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8081
#  servlet:
#    context-path: /beam

beam:
  rest:
    swagger-open: true  #是否开启swagger (true/false)
    auth-open: true #拦截器是否开启(true或者false)
    sign-open: true #签名机制是否开启(true或false)
    file-upload-path: /upload/test      #文件上传目录(不配置的话为java.io.tmpdir目录)
    secret: hsshy        #秘钥
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
log:
  path: beam-rest-logs
