beam:
  admin:
    swagger-open: true  #是否开启swagger (true/false)
    captcha-open: true
    globalSessionTimeout: 21600 #单机环境，session过期时间为6小时
    cluster: false #需要集群 session共享时 改为true pom文件注释打开 BeamAdminApplication类上注解打开
    login-code:
      #  验证码类型配置 查看 LoginProperties 类
      code-type: arithmetic
      #  验证码高度
      width: 111
      #  验证码宽度
      heigth: 36
      # 内容长度
      length: 2
server:
   port: 8080
   tomcat:
     uri-encoding: UTF-8
     max-threads: 1000
     min-spare-threads: 30
   servlet:
     context-path: /beam_ht
log:
  path: beam-admin-logs
